### ISSUE TITLE
Clarify how the keywords and phrases will be used on the web page

### ISSUE THREAD

**Issue by Swapnil62** [rlantigua01/mywebclass-agile-docs#12]
In initiative 5.2 - it would be helpful to clarify how the keywords and phrases will be used on the website. For ex. will they use page titles, URLs, or in the content itself?

**Comment by rlantigua01** [comment]
Acknowledged. The keywords and phrases used for the SEO optimization will be forum titles, URLS, and information presented in the forum itself - like phrases, and specific words
